vim.cmd('set mouse=a')
vim.cmd('set nocompatible')
vim.cmd('set encoding=utf-8')
vim.cmd('set termguicolors')
vim.cmd('set hlsearch')
vim.cmd('set smartcase')
vim.cmd('set incsearch')
vim.cmd('set cursorline')
vim.cmd('set autoindent')
vim.cmd('set nu')
vim.cmd('set relativenumber')
vim.cmd('set showmatch')
vim.cmd('set expandtab')
vim.cmd('set shiftwidth=2')
vim.cmd('set tabstop=2 softtabstop=2')
vim.cmd('set nowrap')
vim.cmd('set encoding=utf-8')
vim.cmd('set noerrorbells')
vim.cmd('set smartindent')
vim.cmd('set noswapfile')
vim.cmd('set undodir=~/.config/nvim/undodir')
vim.cmd('set undofile')
vim.cmd('set splitbelow')
vim.cmd('set splitright')
vim.cmd('syntax enable')
-- vim.cmd('colorscheme onedarker')
vim.cmd('runtime ./plug.vim')
vim.cmd('map <space> <Nop>')
vim.cmd('let mapleader=" "')
vim.cmd('nmap <Leader>s /')
vim.cmd('nnoremap <Leader>o o<Esc>')
vim.cmd('nnoremap th :tabfirst<CR>')
vim.cmd('nnoremap tk :tabnext<CR>')
vim.cmd('nnoremap tj :tabprev<CR>')
vim.cmd('nnoremap tl :tablast<CR>')
vim.cmd('nnoremap tt :tabedit<Space>')
vim.cmd('nnoremap tn :tabnew<CR>')
vim.cmd('nnoremap td :tabclose<CR>')
vim.cmd('nnoremap <leader>q :q<CR>')
vim.cmd('nnoremap <leader><Esc> :q!<CR>')
vim.cmd('nnoremap <leader>h :wincmd h<CR>')
vim.cmd('nnoremap <leader>j :wincmd j<CR>')
vim.cmd('nnoremap <leader>k :wincmd k<CR>')
vim.cmd('nnoremap <leader>l :wincmd l<CR>')
vim.cmd('nnoremap <silent> + :vertical resize +15<CR>')
vim.cmd('nnoremap <silent> - :vertical resize -15<CR>')
vim.cmd('nnoremap j jzz')
vim.cmd('nnoremap k kzz')
vim.cmd('nnoremap G Gzz')
vim.cmd('nnoremap <S-j> <C-d>zz')
vim.cmd('nnoremap <S-k> <C-u>zz')
vim.cmd('nnoremap bn :bnext<CR>')
vim.cmd('nnoremap bv :bprev<CR>')
vim.cmd('nnoremap bd :bd<CR>')
vim.cmd('noremap <esc> :noh <CR>')
vim.cmd('nnoremap <leader>p :Gitsigns preview_hunk<CR>')
vim.cmd('nmap <leader>gs :G<CR>')
vim.cmd('nmap <leader>gc :G commit<CR>')
vim.cmd('nmap <leader>gm :G merge ')
vim.cmd('nmap <leader>go :G checkout ')
vim.cmd('nmap <leader>gj :diffget //3<CR>')
vim.cmd('nmap <leader>gf :diffget //2<CR>')
vim.cmd('nmap <leader>gr wdv<CR><leader>k:q!<CR><leader>l')
vim.cmd('nmap <leader>gl :G log<CR>')
-- vim.cmd('IndentBlanklineDisable')
vim.cmd('nnoremap <C-i> :IndentBlanklineToggle<CR>')
vim.cmd('highlight! CmpItemAbbrDeprecated guibg=NONE gui=strikethrough guifg=#808080')
vim.cmd('highlight! CmpItemAbbrMatch guibg=NONE guifg=#569CD6')
vim.cmd('highlight! CmpItemAbbrMatchFuzzy guibg=NONE guifg=#569CD6')
vim.cmd('highlight! CmpItemKindVariable guibg=NONE guifg=#9CDCFE')
vim.cmd('highlight! CmpItemKindInterface guibg=NONE guifg=#9CDCFE')
vim.cmd('highlight! CmpItemKindText guibg=NONE guifg=#9CDCFE')
vim.cmd('highlight! CmpItemKindFunction guibg=NONE guifg=#C586C0')
vim.cmd('highlight! CmpItemKindMethod guibg=NONE guifg=#C586C0')
vim.cmd('highlight! CmpItemKindKeyword guibg=NONE guifg=#D4D4D4')
vim.cmd('highlight! CmpItemKindProperty guibg=NONE guifg=#D4D4D4')
vim.cmd('highlight! CmpItemKindUnit guibg=NONE guifg=#D4D4D4')
vim.cmd('nnoremap <leader>b :NvimTreeToggle<CR>')
vim.cmd('nnoremap <leader>o :Telescope projects<CR>')
vim.cmd('nnoremap <leader>ff <cmd>Telescope find_files<cr>')
vim.cmd('nnoremap <leader>fg <cmd>Telescope live_grep<cr>')
vim.cmd('nnoremap <leader>fb <cmd>Telescope buffers<cr>')
vim.cmd('nnoremap <leader>fh <cmd>Telescope help_tags<cr>')



require('user.alpha-nvim')
require('user.autopairs')
require('user.bufferline')
--require('user.cmp')
require('user.comment')
require('user.gitsigns')
require('user.indent-blankline')
-- require('user.lspconfig.rc')
-- require('user.lualine.rc')
require('user.null-ls')
require('user.nvim_tree')
require('user.project')
-- require('user.telescope.rc')
require('user.toggleterm')
-- require('user.treesitter.rc')
